### ISSUE TITLE
书上代码看不懂

### ISSUE THREAD

**Issue by dushenda** [ShenghaiRong/suanfasheji2019#19]
书上的好多代码都看不懂，平时可以来找助教问问吗？😔

**Comment by ShenghaiRong** [comment]
课本写的不好，最好看老师ppt和算法导论。同时这是算法课，不必太纠结于代码的实现，掌握算法思想是关键，所以纸质作业也不要求写代码。

**Comment by FantDing** [comment]
可以提issue大家一起看看
