### ISSUE TITLE
请问分支限界法为什么上下界都要算？

### ISSUE THREAD

**Issue by season95** [ShenghaiRong/suanfasheji2019#26]
请问分支限界法为什么上下界都要算？老师提了一句说为了尽早更新当前最优值，但是不太理解。感觉只需要根据优化目标算其中一个啊？望助教和大神萌指点！

**Comment by FantDing** [comment]
比如你要`min f(x)`, 过程中要剪枝，当`sub(f(x'))`<best才不剪枝，而分支限界比较难直接到叶节点，因此需要提前估计一个best，对于best的估计不能太小（太小的话就会把有可能的正确解给剪掉了），因此使用上界估计；又由于剪枝需要f(x')的下界，因此需要估计下界。

- 对于`只需要根据优化目标算其中一个`：如果只计算`sub(f(x'))`的话，你的best只有等到搜索到叶子节点才能得到，太迟了

**Comment by season95** [comment]
谢谢助教！
