### ISSUE TITLE
有没有对一下选择题答案的？

### ISSUE THREAD

**Issue by dushenda** [ShenghaiRong/suanfasheji2019#32]
我做的选择题答案： 
**1~5**        ABCCB
**6~10**      BCACA
**11~15**    BCCCA
**16~20**    BBDDB

**Comment by byl0561** [comment]
1~5      A B CD C B
6~10    B C A AC A
11~15  B C C C B
16~20  B B D D B

**Comment by dushenda** [comment]
都忘了这个有多选题🛰
